### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Calinou** [wheybags/glibc_version_header#1]
This repository currently has no license included; a license should be added. Since this repository contains portions based on glibc, it may have to use the same license as glibc.

**Comment by Zennoe** [comment]
Without a licence your project is NOT under public domain. You are still the copyright holder.
Also just as Calinou said, make sure to choose a compatible licence (e.g. the same as glibc).

**Comment by wheybags** [comment]
This project is just a header which specifies versions, it doesn't need to have the same license as glibc.
That said, I just completely forgot to add a license, will add one now

**Comment by wheybags** [comment]
closed via https://github.com/wheybags/glibc_version_header/commit/1b37b2a0e115a70828155661a69451f19f59938a

**Comment by thejcannon** [comment]
Can you copyright-stamp the headers themselves with the license? Otherwise consumers need to use both the `LICENSE` file and the header.
