### ISSUE TITLE
confusing explanation in README

### ISSUE THREAD

**Issue by kwrodarmer** [wheybags/glibc_version_header#5]
Hello - in your README, you mention,

"we only add the magic symver directives for these pthreads functions if _REENTRANT is defined."

yet in the include files you have

`
#ifndef _REENTRANT 
__asm__(".symver pthread_cond_destroy,pthread_cond_destroy@GLIBC_2.3.2"); 
#endif
`

This leaves me confused - it appears you are defining a magic symver directive only when _REENTRANT is undefined. Could you explain?

**Comment by wheybags** [comment]
Whoops, I messed up while refactoring, the readme is correct and code is wrong, will push a fix soon

**Comment by wheybags** [comment]
fixed by https://github.com/wheybags/glibc_version_header/commit/77c80e0d84c3ed5084c6cf1fd9a2d4aaa1499ec8
